### ISSUE TITLE
RaspberryPi .iso - collection of ideas/concerns

### ISSUE THREAD

**Issue by smoe** [LinuxCNC/buster-live-build#12]
I just thought I bring this up to collect what comes to mind.
* Realtime Kernel - any issues?
* Frequency variations - just keep it at max?
* RPi-tailored software that we may otherwise miss?
* What about Odroids et al. ? 

Other bits and pieces?

**Comment by sebastiankuzminsky** [comment]
I recently played around with the Debian (not Raspberry PI OS, formerly known as Raspbian) bookworm aarch64  RPi4 image (2022-08-08) from <https://raspi.debian.net/>.  It's built from <https://salsa.debian.org/raspi-team/image-specs>.

The good:
* The system worked well and was completely stable.  Console, serial console, and Wifi all worked without any drama. 
* The `image-specs` build system was straightforward and easy to use and extend.
* The "default" realtime kernel (linux-image-rt-arm64) gave ok latency results (<100 µs) with the kernel cmdline `irqaffinity=0-2 rcu_nocbs=3 rcu_nocb_poll isolcpus=domain,managed_irq,3 sysctl.kernel.sched_rt_runtime_us=-1`.
* As an experiment, with an [unfinished half-baked busywait-based timing mode](https://github.com/LinuxCNC/linuxcnc/tree/busywait5) for the realtime threads (as opposed to the current, well-tested clock_nanoslee()-based timing mode) I got latencies in the single-digit microseconds.

The bad:
* One of the things that make the Raspberry so cool is how flexible the "GPIO port" is.  In Raspberry PI OS you can load device-tree overlays to turn on and off different features there, like the SPI uarts and the GPIO pins.  I could not get any of this stuff to work on Debian.  The Raspberry Pi OS kernel has extensive [out-of-tree kernel patches](https://github.com/raspberrypi/linux) to enable dynamic (i.e. runtime, not just boot-time) device-tree overlays, and big changes to the RPi device-tree sources (including the addition of overlays to help enable/distable stuff on the GPIO port).  There are [special userland tools](https://github.com/raspberrypi/userland/) to help with all that.  The userland tools compile and run on Debian Bookworm, but the DTS and kernel patches are of course missing from the debian kernel so they don't work.  So no SPI, until someone smarter comes along and fixes it.  :-( 
* Because of that, I could not get the 7i90 or 7c80 to work.  Possibly the Ethernet-based Mesa cards would work, but I did not try.
* I similarly could not figure out how to enable the GPIO pins.  Poking `/sys/class/gpio/export` like one does in Raspberry Pi OS did not work.  :-(
* The system boots directly from the RPi firmware to a designated kernel image, no grub or uboot, so it's somewhat inconvenient to switch between kernels.

**Comment by smoe** [comment]
I did some googleing and the entertaining blog entry https://waldorf.waveform.org.uk/2021/the-pins-they-are-a-changin.html pointed me to http://abyz.me.uk/lg/py_lgpio.html .

**Comment by andypugh** [comment]
PCW has noted that you need to use ntpd rather than timesyncd
https://forum.linuxcnc.org/38-general-linuxcnc-questions/46340-jittery-stepper-pulses-with-mesa-7i76e-solved?start=10#256153

**Comment by SebKuzminsky** [comment]
> https://waldorf.waveform.org.uk/2021/the-pins-they-are-a-changin.html

This points to [gpiod](https://wiki.loliot.net/docs/lang/python/libraries/gpiod/python-gpiod-about/), which is [available in Debian](https://packages.debian.org/search?keywords=gpiod) and which does indeed let you twiddle the GPIO pins from userspace, so that's a good step forward.

But it doesn't help with the missing SPI - there's still no way to enable the SPI uart as far as i can see.

**Comment by smoe** [comment]
Please also follow that link to the lg library, this https://github.com/joan2937/lg I understand to be the github repository of it, which states to also be supporting SPI. I have not found it on Debian, but Ubuntu has it as https://launchpad.net/ubuntu/+source/lg-gpio .

**Comment by SebKuzminsky** [comment]
I looked briefly at that and I think I just calls `open()` on `/dev/spidev`, which doesn't do the trick.

The problem is that `/dev/spidev*` only exists if the device-tree says it should exist, and the dts in the kernel.org kernel says it should *not* exist.  The raspbian kernel has extensive changes and additions to the dts, and changes to the kernel itself to allow loading dtb overlays at runtime, to do things like enable the SPI uarts.

**Comment by rodw-au** [comment]
This issue can be closed because we have a seperate repo for the Raspberry pi that addressses all of the concerns mentioned.
Ref: https://github.com/LinuxCNC/rpi-img-builder-lcnc

Recommend this issue be closed
